baseURL = "https://zhongjzsb.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "zhongjzsb"
theme = "hugo-theme-hello-friend-ng"
ignoreFiles = [
  "\\.Rmd$",
  "\\.Rmdtest$", # the test Rmd files
  "\\.Rmarkdown$",
  ".Rprofile",
  ".Rhistory",
  ".Rproj",
  "_files$",
  "_cache$",
  "others/.*",
  "src/.*",
  "content/test/.*"
] # "layout/.*"

enableGitInfo = false
pygmentsCodefences  = true
pygmentsUseClasses  = true
# hasCJKLanguage = true  # If Chinese/Japanese/Korean is your main content language, enable this to make wordCount works right.
rssLimit = 10  # Maximum number of items in the RSS feed.
# copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
# copyright = "&copy; Jingyu Bao & Jackie Liu, {year}"
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
googleAnalytics = "UA-159320532-1"
disqusShortname = "zhongjzsb"

[author]
  name = "Jingyu Bao"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"

  # ----------
  # add author
  # author = "authors"

  # disableKinds = ["taxonomyTerm"] # to disable authors.

  # Reference: https://www.netlify.com/blog/2018/07/24/hugo-tips-how-to-create-author-pages/

  # -------
  # Categories are disabled by default.
  category = "categories"


[permalinks]
   post = "/:section/:year/:month/:day/:slug/"
   # post = "/:section/"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  author = "Jingyu Bao" # create default author
  # bio = "something about zhongjzsb"
  comment = true # add comment option in post

  # Metadata mostly used in document's head
  description = "something about zhongjzsb"
  images = [""]
  # themeColor = "#494f5c"

  homeSubtitle = "Life is a long memory time series"
  footerCopyright = '&#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  bgImg = "/images/special-bulb-york-mills.jpg"  # Homepage background-image URL

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = "https://github.com/username/repository/commit/"

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.
  relatedPosts = false  # Add a related content section to all single posts page
  code_copy_button = false # Turn on/off the code-copy-button for code-fields

  # Add custom css
  customCSS = ["/assets/style.css"]

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/zhongjzsb"

  [[params.social]]
    name = "twitch"
    url = "https://www.twitch.tv/zhongjzsb"

  [[params.social]]
    name = "linkedin"
    url = "http://linkedin.com/in/jingyu-bao"

  [[params.social]]
    name = "github"
    url = "https://github.com/zhongjzsb"

  [[params.social]]
    name = "email"
    url = "mailto:zhongjzsb@gmail.com"

  # ---------------
  # copy from original config

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "github"
  MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
  MathJaxVersion = "2.7.5"

  # path to the favicon, under "static"
  favicon = "favicon.ico"

  # for hello-friend-ng
  [languages.en.params.logo]
      logoText = "/home/jingyu"
      logoHomeLink = "/"

  [params.logo]
  url = "logo.png"
  width = 50
  height = 50
  alt = "Logo"


[menu]

  [[menu.main]]
    name = "Baobao"
    url = "/posts/baobao-posts/"
    weight = 10

  [[menu.main]]
    name = "Jackie"
    url = "/posts/jackie-posts/"
    weight = 20

  # [[menu.main]]
  #   name = "Notes"
  #   url = "/notes/"
  #   weight = 20

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 30

  [[menu.main]]
    name = "Archive"
    url = "/tags/"
    weight = 50


  # [[menu.main]]
  #   name = "Book"
  #   url = "https://book.zhongjzsb.com"
  #   weight = 40
